// <auto-generated />
using System;
using KutuphaneMVC2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KutuphaneMVC2.Migrations
{
    [DbContext(typeof(KutuphaneContext))]
    [Migration("20250424191617_AddSampleUsers")]
    partial class AddSampleUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("KutuphaneMVC2.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YetkiSeviyesi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AdminId");

                    b.ToTable("Adminler");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Ad = "Admin",
                            AktifMi = true,
                            Email = "admin@kutuphane.com",
                            KullaniciAdi = "admin",
                            Sifre = "Admin123!",
                            SonGirisTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Soyad = "User",
                            YetkiSeviyesi = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("KutuphaneMVC2.Models.Kitap", b =>
                {
                    b.Property<int>("KitapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BasimYili")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StokDurumu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YayinEvi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KitapId");

                    b.ToTable("Kitaplar");

                    b.HasData(
                        new
                        {
                            KitapId = 1,
                            Aciklama = "Klasik Rus edebiyatının başyapıtlarından biri",
                            BasimYili = 2020,
                            EklenmeTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "978-975-458-717-0",
                            Kategori = "Roman",
                            KitapAdi = "Suç ve Ceza",
                            SayfaSayisi = 704,
                            StokDurumu = true,
                            YayinEvi = "İş Bankası Kültür Yayınları",
                            Yazar = "Fyodor Dostoyevski"
                        },
                        new
                        {
                            KitapId = 2,
                            Aciklama = "Distopik edebiyatın en önemli eserlerinden biri",
                            BasimYili = 2019,
                            EklenmeTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "978-975-07-1029-4",
                            Kategori = "Distopik Roman",
                            KitapAdi = "1984",
                            SayfaSayisi = 352,
                            StokDurumu = true,
                            YayinEvi = "Can Yayınları",
                            Yazar = "George Orwell"
                        });
                });

            modelBuilder.Entity("KutuphaneMVC2.Models.KitapOdunc", b =>
                {
                    b.Property<int>("OduncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AlinmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BeklenenIadeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KitapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OduncId");

                    b.HasIndex("KitapId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KitapOdunc");
                });

            modelBuilder.Entity("KutuphaneMVC2.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UyelikTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            KullaniciId = 1,
                            Ad = "Ahmet",
                            Adres = "İstanbul, Türkiye",
                            AktifMi = true,
                            Email = "ahmet@example.com",
                            Sifre = "Kullanici123!",
                            SonGirisTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Soyad = "Yılmaz",
                            Telefon = "5551234567",
                            UyelikTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("KutuphaneMVC2.Models.KitapOdunc", b =>
                {
                    b.HasOne("KutuphaneMVC2.Models.Kitap", "Kitap")
                        .WithMany()
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KutuphaneMVC2.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Kullanici");
                });
#pragma warning restore 612, 618
        }
    }
}
